export const ADD_MISSIONMEC = "ADD_MISSiONMEC";
export const MODIFY_MISSIONMEC = "MODIFY_MISSIONMEC";
export const DELETE_MISSIONMEC = "DELETE_MISSIONMEC";
export const MODIFY_MISSIONMEC_STATUS = "MODIFY_MISSIONMEC_STATUS";
