const data = [
  {
    id: 1,
    numero: "123",
    date: "2021-06-29",
    client: "Simsoft",
    typeFacture: "Type 1",
    vehicule: "Peugot",
    remorque: "R1",
    chauffeur: "Ahmed",
    representant: "Ali",
    nBT: "1648",
    dateBT: "2021-03-08",
    nBonReception: "15",
    dateBonReception: "2021-03-09",
    produit: "Blé",
    unite: "Kg",
    lieuDepart: "Sousse",
    lieuArrive: "Gabes",
    distance: "250",
    quantite: "1000",
    ecartPoids: "500",
    etat: "attente",
  },

  {
    id: 2,
    numero: "456",
    date: "2021-06-29",
    client: "ISITCOM",
    typeFacture: "Type 3",
    vehicule: "Citroen",
    remorque: "R3",
    chauffeur: "Wajdi",
    representant: "Samir",
    nBT: "1648",
    dateBT: "2021-03-08",
    nBonReception: "15",
    dateBonReception: "2021-03-09",
    produit: "Papier",
    unite: "Kg",
    lieuDepart: "Sousse",
    lieuArrive: "Gabes",
    distance: "250",
    quantite: "100",
    ecartPoids: "5",
    etat: "annulée",
  },

  {
    id: 3,
    numero: "456",
    date: "2021-06-29",
    client: "ISITCOM",
    typeFacture: "Type 3",
    vehicule: "Citroen",
    remorque: "R3",
    chauffeur: "Wajdi",
    representant: "Samir",
    nBT: "1648",
    dateBT: "2021-03-08",
    nBonReception: "15",
    dateBonReception: "2021-03-09",
    produit: "Papier",
    unite: "Kg",
    lieuDepart: "Sousse",
    lieuArrive: "Gabes",
    distance: "250",
    quantite: "100",
    ecartPoids: "5",
    etat: "effectuée",
  },

  {
    id: 4,
    numero: "456",
    date: "2021-06-29",
    client: "ISITCOM",
    typeFacture: "Type 3",
    vehicule: "Citroen",
    remorque: "R3",
    chauffeur: "Wajdi",
    representant: "Samir",
    nBT: "1648",
    dateBT: "2021-03-08",
    nBonReception: "15",
    dateBonReception: "2021-03-09",
    produit: "Papier",
    unite: "Kg",
    lieuDepart: "Sousse",
    lieuArrive: "Gabes",
    distance: "250",
    quantite: "100",
    ecartPoids: "5",
    etat: "en_cours",
  },
];

export default data;
